### ISSUE TITLE
if condition for render html or partial

### ISSUE THREAD

**Issue by hvbnet** [dondido/express-es6-template-engine#10]
I need to render some section in html by if condition
for example thymeleaf has follow option:
` <div th:if="${user.isAdmin()} == false"> ...`
therefore section render if user has admin role
how it possible?
thanks in advanced

**Comment by dondido** [comment]
Yeap, it's definitely possible. My approach would be to have something like this:
`${user.isAdmin() == false ? '<div class="a">`${user.fullName}`</div>' : '<div class="b"></div>'}`
