### ISSUE TITLE
ReferenceError is not defined

### ISSUE THREAD

**Issue by icetee** [dondido/express-es6-template-engine#13]
I check exists object in template, if exists then work good. But if no exists I get exception `ReferenceError: e is not defined`. Do I know somehow?

```
<input type="text" id="username" name="username" placeholder="Username" class="text ${(e) ? 'error' : ''}" autocomplete="off">
```

**Comment by dondido** [comment]
How do you compile the template literal? Is it by using `es6Renderer('template', {locals});
`

**Comment by christiaanwesterbeek** [comment]
Wow, yeah I got this too. And here it is; a days old issue with the same. Cool :)

In my case, the template uses a variable that is not in locals.

The actual problem is: **It's not catchable so the server dies**.

I tried:

```javascript
res.render('template', { locals }, err => {
    next(createError(500, `Template error: ${err.toString()}`))
})
```

And 

```javascript
try {
   res.render('template', { locals })
} catch (err) {
    next(createError(500, `Template error: ${err.toString()}`))
}
```
In both instances, the web server dies. I need to fix my variables. I know. But I also want to protect my server against a rogue commit to my template variables and nicely show a 500 page instead of ending up with a dead web server.

**Comment by icetee** [comment]
> How do you compile the template literal? Is it by using es6Renderer('template', {locals});

Is correct:
```
router.get('/test', (req, res) => {
  return res.render('test', {
    locals: {
      maintainedBy:  'Good Samaritans'
    }
  });
});
```

(Not) correct:
```
router.get('/test', (req, res) => {
  return res.render('test', {
    locals: {}
  });
});
```

Template
```
S6 Renderer is ${maintainedBy ? `a template engine maintained by ${maintainedBy}` : 'not maitaned anymore'}.
```

The problem is that the variable can't always be guaranteed defined. For example, there is a form if not ok, then has error message, but default not defined.

If I want to re-use the template, I think. For each request, you should set a default value.

Template so you can not even check :(

So far, every template system I've used has caught the error. That's why I created the issue.

**Comment by christiaanwesterbeek** [comment]
I made the smallest possible bit of code loosley extracted from es6-renderer.js that reproduces the problem.

Consider
```javascript
const render = (string, locals) => {
  const localsKeys = Object.keys(locals);
  const localsValues = Object.values(locals);
  const output = new Function(...localsKeys, `return \`${string}\`;`)(...localsValues);
  return output;
}
```

`render('xxx ${foo}', {foo: 'bar'})`

> "xxx bar"

`render('xxx ${foo}', {foo2: 'bar'})`

>  :3 Uncaught ReferenceError: foo is not defined
>      at eval (eval at render (newtab?ie=UTF-8:4), <anonymous>:3:15)
>     at render (<anonymous>:4:70)
>     at <anonymous>:1:1

If you would rewrite render to try catch just the function calling on the values
```javascript
const render = (string, locals, callback) => {
  const localsKeys = Object.keys(locals);
  const localsValues = Object.values(locals);
  const fn = new Function(...localsKeys, `return \`${string}\`;`)
  
  try {
    callback(null, fn(...localsValues));
  } catch(e) {
    callback(e)
  } 
}
```

Now we can reproduce the same error, but this time it is caught.

```javascript
render('xxx ${foo}', {foo2: 'bar'}, (err, output) => {
  if (err) console.log('caught error', err);

  console.log(output)
})
```

This way you would catch the error. Make sure to use app.render'd third parameter which is the callback function.

**Comment by icetee** [comment]
Yeah, so he catches error. The server does not die. But my problem is not solved. Every variable should give a default value. I looked it up, maybe my solutions this:

```javascript
const defineAllVariables = function(template, locals) {
  const localsDef = locals;
  const pattern = /\$\{[\s]*?([\w\d]+)[\s]*?[\}\?]/gm;

  let matchArray;
  while((matchArray = pattern.exec(template)) !== null) {
    if (!locals.hasOwnProperty(matchArray[1])) {
      localsDef[matchArray[1]] = null;
    }
  }

  return localsDef;
};

const render = (string, localsDef, callback) => {
  const locals = defineAllVariables(string, localsDef);
  const localsKeys = Object.keys(locals);
  const localsValues = Object.values(locals);

  const fn = new Function(...localsKeys, `return \`${string}\`;`);

  try {
    callback(null, fn(...localsValues));
  } catch(e) {
    callback(e)
  }
}

render('xxx ${foo ? "ok" : "error"}', {foo2: 'bar'}, (err, output) => {
  if (err) console.log('caught error', err);

  console.log(output)
});
```

I do not know how good a performance is.

**Comment by dondido** [comment]
@christiaanwesterbeek @icetee 
Ok this is a pretty serious concern:
> The actual problem is: It's not catchable so the server dies. 

Just made a commit that addresses the issue by adding `try catch` statement. The commit also introduces function decorator, that transforms callbacks into promises (while preserving the backwards compatibility) and allows native error handling by using `resolve` and `reject` functions.

@icetee I've made some useful (that is in my opinion) comments on the PR, so please have a look and do not hesitate to discuss it if you feel like it.

**Comment by jmsherry** [comment]
@dondido Maybe I'm misunderstanding but I'm still getting this error! 

```javascript
app.get('/about', function(req, res) {
  res.render('about', {
      locals: {
        title: 'About!',
        // loggedIn: true //<-- missing variable
      },
      partials: {
        header: 'header',
        footer: 'footer',
      },
    }, (...args) => {
      console.log('args', args); // never fires
    });
});
```
What's the correct way to catch errors?

Thanks :)

**Comment by dondido** [comment]
Hey @jmsherry , I have just added an extra test case: https://github.com/dondido/express-es6-template-engine/blob/master/test/es6-renderer.spec.js

Here it is:

`it("throws an error when variable is not found", done => {
      app.render(
        "index",
        {
          locals: {},
          partials: {
            footer: "partial"
          }
        },
        (err) => {
          expect(err instanceof Error).to.equal(true);
          expect(err.message).to.equal('engineName is not defined');
          done();
        }
      );
    });`

**Comment by jmsherry** [comment]
Thanks @dondido,
I've created a demo here: https://github.com/jmsherry/server-side-templating-es6/tree/fault

If you start the project normally it'll work on the index page but if you navigate to the `about` page you'll get the fault.

Thanks

**Comment by dondido** [comment]
@jmsherry well spotted! Just applied the fix, so pull in the latest :)

**Comment by kczx3** [comment]
So is it still not possible to handle a local variable that wasn't passed?  Or do we always have to ensure that all locals the template expects are passed?

**Comment by dondido** [comment]
The solution a lot of people seem to gravitate toward is to wrap variables in an object, like so:
```
const text = '${$.engineName} - The fastest javascript template string engine in the whole ${$.place}!';
es6Renderer(text)({ engineName: 'ES6 Renderer'});
// ES6 Renderer - The fastest javascript template string engine in the whole !
```
Although property 'place' was not provided the string compilation still worked. In cases like these this ES6 renderer online compiler might be usefull: http://dondido.github.io/express-es6-template-engine/

**Comment by lachieh** [comment]
Another alternative is to use a ternary with a `typeof` check:
```js
${ typeof error !== 'undefined' && error ? `<div class="error">${error}</div>` : '' }
```
