### ISSUE TITLE
partial is not loading. Log shows no such file or directory.

### ISSUE THREAD

**Issue by fuad008** [dondido/express-es6-template-engine#15]
Here are the screenshots! 
<img width="386" alt="screen shot 2018-11-09 at 4 24 25 pm" src="https://user-images.githubusercontent.com/4208018/48294921-706a8580-e43c-11e8-830f-54d7f3d05055.png">
<img width="924" alt="screen shot 2018-11-09 at 4 24 42 pm" src="https://user-images.githubusercontent.com/4208018/48294924-75c7d000-e43c-11e8-8310-0465a2ebb862.png">

I am using MacOS and node version 10.13.0. 

The engine compiles perfectly if I don't use partials at all, but as soon as I add partials, it can't find the file anymore. It was supposed to look for partial files in "views" directory, but the screenshot shows that it is looking for the partials in the "routes/views/" directory.

Thank you in advance!

**Comment by fuad008** [comment]
Hello, dondido! Thank you for a prompt reply! Yes, my views directory is in "...Desktop/ecom/views"

I have tried that before, but the problem persists.  Here are the screenshots:
<img width="380" alt="screen shot 2018-11-10 at 12 44 22 pm" src="https://user-images.githubusercontent.com/4208018/48305845-f3e0b100-e4e6-11e8-9f70-49631279321d.png">
<img width="699" alt="screen shot 2018-11-10 at 12 44 40 pm" src="https://user-images.githubusercontent.com/4208018/48305847-f9d69200-e4e6-11e8-8f8d-8a625a5ab0cf.png">

**Comment by dondido** [comment]
Glad to hear that :)
