### ISSUE TITLE
Error not get upper

### ISSUE THREAD

**Issue by evilz** [dondido/express-es6-template-engine#16]
Hi,

I'm using it and it's pretty cool 👍 
But I don't understand how to get error back ?
I'm using it with express. Do I need to add a callback or some try/catch or anything ?

Thank

**Comment by dondido** [comment]
Hi @evilz,
excellent spot! Just improved error handling for callback functions which was not processed the way it should. So please, don't hesitate and grab the latest version 2.1.6. This also made me include 'Error handling section' in the README file:

> ES6 Renderer catches and processes errors that occur both synchronously and asynchronously. ES6 Renderer comes with a default error handler so you don’t need to write your own to get started. Errors that occur in synchronous code require no extra work. If synchronous code throws an error, then ES6 Renderer will catch and process it. For example.
> 
```
 const text = '${engineName} - The fastest javascript template string engine in the whole ${place}!';
 const err = es6Renderer(text, 'engineName')('ES6 Renderer', 'multiverse');
 expect(err instanceof Error).to.equal(true);
```
> For errors returned from asynchronous functions, you must pass them to the callback function, where ES6 Renderer will catch and process them. A viable alternative will be to use native promise catch or reject methods. The example underneath handles both cases simultaneously:
> 
```
es6Renderer(
     __dirname + "/index.html",
     { locals: { engineName: "ES6 Renderer", footer: "MIT License" } },
     (err) => expect(err instanceof Error).to.equal(true);
 ).then((err) => expect(err instanceof Error).to.equal(true));
```
>

**Comment by evilz** [comment]
cool,

I just update, but I think it still some black hole :p

Looks like when partial file does not exist error is not throw up.

**Comment by dondido** [comment]
Ok fixed that one too, thank you for reporting it. Just grab the latest

**Comment by evilz** [comment]
Just works :+1 
Sorry, I was not able to test this before.

Thank.

By the way I use  `.marko` file so I can use marko extension in VS code. :p
