### ISSUE TITLE
can't get values

### ISSUE THREAD

**Issue by ItsMeMIHIR** [dondido/express-es6-template-engine#20]
hi
how can i use my locale in locale.
my locale is like is
`res.render('index', {locals: {product: [
  {
  name: 'github',
  user: 'Mihir'
  }`

i want to use in html like

`${product.name}`
`${product.user}`

**Comment by ItsMeMIHIR** [comment]
how i create my locale so
i can use like this
`${product.name}
${product.user}`

**Comment by dondido** [comment]
Try with the following syntax: `res.render('index', { locals: { product: { name: 'github', user: 'Mihir' } } })`
