### ISSUE TITLE
Suggestion to show at README a console.log example

### ISSUE THREAD

**Issue by ppKrauss** [dondido/express-es6-template-engine#21]
The first test that we do when using simplest `node myExample.js` , with standalone `require('express-es6-template-engine')` is something like `console.log("Hello world!")`... How to do it??

**Comment by ppKrauss** [comment]
... That is

**Comment by ppKrauss** [comment]
(oops, not closed!!)  

... That is, interesting to complete the README with a standalone code 

```js
const es6Renderer = require('express-es6-template-engine');
es6Renderer(
    __dirname + '/views/index.html',
    { locals: { title:  'ES6 Renderer' } },
    (err, content) => err || content
).then(function(result) {
    console.log(result);
});

```

**Comment by dondido** [comment]
Depending on the code structure there are two (2) ways of calling the `es6Renderer` function: `sync` and `async`. Although both ways look quite similar, they differ in the numbers and the order of parameters passed.
Q: how to use es6Renderer in a variable, `let t = es6Renderer()`?
A: 

1. Sync way:
`
const titleTpl = '${engineName} - The fastest javascript template string engine!';
// The returned function is called with a string representation of an array of variable values.
const compiled = es6Renderer(titleTpl, 'engineName')('ES6 Renderer');
`
The `compiled` variable from the code above is assigned with a string value of `ES6 Renderer - The fastest javascript template string engine!`
Another way of using it synchronously is:
`
const text = '${$.engineName} - The fastest javascript template string engine in the whole ${$.place}!';
console.log(es6Renderer(text)({ engineName: 'ES6 Renderer', place: 'multiverse' });
` 

2. Async way:
`
const compile = es6Renderer(__dirname + '/views/template.html', {
  locals: {
    title:  'ES6 Renderer'
  },
  partials: {
    template: __dirname + '/views/partial.html'
  }
}, (err, content) => err || content);
compile.then(output => res.send(output))
`
