### ISSUE TITLE
Suggestion put count in Iterators

### ISSUE THREAD

**Issue by ItsMeMIHIR** [dondido/express-es6-template-engine#22]
`res.render('partial-iteration', {
    locals: {
      features:  [
      { 
        dt: 'Multi-line strings', 
        dd: 'Any new line characters inserted in the source are part of the template string.' 
      },
      { 
        dt: 'Expression interpolation', 
        dd: 'Template strings can contain placeholders. These are indicated by dollar sign and curly braces.' 
      },
    ]
    }
  });`

`${features.count}`
like this.
i want to show features.count
result 2

**Comment by dondido** [comment]
try with array length property: `${features.length}`
