### ISSUE TITLE
Array iteration key in partial

### ISSUE THREAD

**Issue by antb-developer** [dondido/express-es6-template-engine#23]
courseGridView is partial, I want to use f in this partial
```
									${courses.map(f => `
										<div class="list-item">
											<dt>${f._id}</dt>
											${courseGridView}
										</div>
								  `).join('')}


```

**Comment by dondido** [comment]
Hey I see nothing wrong with that - should work as expected as long as `courseGridView` is defined

**Comment by antb-developer** [comment]
I cant use in partial, ${f._id}.
Since f is not known to partial

**Comment by dondido** [comment]
Template nesting is currently not supported by the engine. A simple workaround to this issue would be to perform multiple template compilations.
