### ISSUE TITLE
Mapping "locals" in React

### ISSUE THREAD

**Issue by neillindberg** [dondido/express-es6-template-engine#28]
Hello,

This library got me so much closer to the end goal of a server-side rendered React page with a few params passed along.

Everything breaks when I go to map an array of object. The React code itself works great with sample data, hardcoded, but when I pass along the rows array in the `res.render` call everything breaks. Can these params not be destructured?
`${rows.sort(sortOnExpiry).map(({ item, expiry_date, serial }) => {`

Or, maybe I'm not referring to these correctly?
`<div className='expiry-letter--main-cod-table-tr' key={serial}>`

Thanks for any insight. This is so fast I'm really hoping I can use it for this React-turned-server-side w/ Puppeteer-to-PDF thing I'm doing.

Neil

**Comment by neillindberg** [comment]
Are the params somehow extractable for use in JS? Something similar to handlebars, maybe? `const localCustomer = {{${customer}}};`? This is not working, I tried several forms.

**Comment by dondido** [comment]
Hi there, `key={serial}` should become `key={${serial}}`. As with regards with the second issue if you expect an object I would recommend something like: `const localCustomer = JSON.parse(${JSON.stringify(customer)});`
