### ISSUE TITLE
I love this middleware

### ISSUE THREAD

**Issue by devotis** [dondido/express-es6-template-engine#3]
This is exactly what I needed. Just simple enough and uses just fs and template literals. Thanks.

**Comment by Globik** [comment]
And I don't love this middleware. It's archaic beside I'm not a big fan of new Function() and staff like that.
Es6 template literals working  by nature great without new Function. Тольк огород городить с new Function()

**Comment by christiaanwesterbeek** [comment]
Calling template literals archaic is a bit of an exaggeration. Oh and you cannot construct a template literal from a string (file contents) without the use of Function (or eval). Using Function for that is the way to go. Reference: https://stackoverflow.com/questions/29771597/how-can-i-construct-a-template-string-from-a-regular-string

**Comment by Globik** [comment]
@christiaanwesterbeek  yes, I know about Function and eval.
Personally I'm prefering the hardcoded literals expressions. Also in conjuction with hotreloader module for uncache the modules. I did it so:
https://github.com/Globik/alikon/blob/master/libs/render.js

And one of the "hardcoded" literal string as a module for the html output:
https://github.com/Globik/alikon/blob/master/views/bitaps.js
