### ISSUE TITLE
partials inside partials

### ISSUE THREAD

**Issue by svbeon** [dondido/express-es6-template-engine#5]
Hi,

So, i've encontered a minor issue that's solvable on my end with precompiling, but i'd rather see that i dont need to.

I basically need to use a partial inside a partial as follows

```
app
+-index
  +-articles
```

as articles is a partial i want to use on multiple pages without the rest of the index page content, however, if i have a `server.js` with the following
```js
...
res.render('app', {
  locals: {
    articlesArray, moment, marked
  },
  partials: {
    template: 'partials/index',
    articles: 'partials/articles'
  }
})
...
```
`app.html`
```html
...
<div>${template}</div>
...
```
`index.html`
```html
...
<div>${articles}</div>
...
```
`articles.html` 
```html
...
${articlesArr.map(el => `
  <div class="article">
    ${(articlesArr.length > 1 ? `<a href="/nyheter/${el.id}">` : '')}
  <h2>${el.title}</h2>
  ${(articlesArr.length > 1 ? `</a>` : '')}
    <span class="date">${moment(el.date, 'x').format('lll')}</span>
    <div>${marked(el.content)}</div>
  </div>`).join('')}
...
```

this will render as the following:

```html
...
<div>
  <div>
    ${articlesArr.map(el => `
    <div class="article">
      ${(articlesArr.length > 1 ? `<a href="/nyheter/${el.id}">` : '')}
    <h2>${el.title}</h2>
    ${(articlesArr.length > 1 ? `</a>` : '')}
      <span class="date">${moment(el.date, 'x').format('lll')}</span>
      <div>${marked(el.content)}</div>
    </div>`).join('')}
  </div>
</div>
...
```

instead of the supposed
```html
...
<div>
  <div>
    <div class="article">
      <h2>${el.title}</h2>
      <span class="date">Jun 13, 2017 00:01</span>
      <div>This is some content that has ben generated properly</div>
    </div>
  </div>
</div>
...
```
whilst i could probably solve it by rendering the articles partial and feed it as a local, it would be nice if it could be done natively in res.render

and while it's specified in the README, it would be a ice function to have, especially since es6Renderer() only ever returns undefined for me

**Comment by dondido** [comment]
Hi Svante, I'm fully aware of the limitation of having no nested partials. I've got the code at hand and if you want me I can commit it in a separate branch. The only thing the stops me merging this code into master is performance degradation - I want to keep **es6Renderer** as fast as possible (currently almost twice as fast as the fastest template engines on the market - **Pug** and **Marko**).

As in regards to `es6Renderer()` function output, it is only returned as a compiled string when the call is made synchronously.

**Comment by svbeon** [comment]
Hi, that'd be wonderful! I could perhaps try to fiddle a bit with that code and see if I can do somet

**Comment by svbeon** [comment]
Also, perhaps you should move the contents of `docs/` to the root of the branch gh-pages? And perhaps expand it with the content of `README.md` would be a great way to find this wonderful project on the web
