### ISSUE TITLE
SyntaxError: Unexpected token = on express-es6-template-engine/es6-renderer.js:3

### ISSUE THREAD

**Issue by reubenlillie** [dondido/express-es6-template-engine#8]
OS: Ubuntu 16.04
kernel: 4.4.0-112-generic
nodejs: 4.2.6
express: 4.16.2
express-es6-template-engine: 2.0.3

The engine looks great, if I can get past this syntax error.

<code>~/node_modules/express-es6-template-engine/es6-renderer.js:3</code>
<code>const compile = (content, $ = '$') => Function($, 'return &grave;' + content + '&grave;;');
</code>
<code>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
</code>

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/PATH/app.js:5:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

For context, /PATH/app.js:5:21 is the require statement:

`const es6Renderer = require('express-es6-template-engine')`

Please advise.

**Comment by dondido** [comment]
This issue is more likely due to node version incompatibility, The engine requires Node version 4.0 or higher. Think this is still an issue with 4.2.6. Try running it with --harmony tag like this node --harmony index or updating to a newer version. Let me know if this one works for you.

**Comment by reubenlillie** [comment]
Thanks for the prompt reply. I found the cause: I was still using the default `nodejs` command for Ubuntu 16.04 instead of `node`. Your code runs with and without the `--harmony` flag, as long as it's `node` or `node --harmony`. But, for clarity, `nodejs` and `nodejs --harmony` both throw the syntax error.
