### ISSUE TITLE
Partials: Template Docs clarification

### ISSUE THREAD

**Issue by theFuzzyWarble** [dondido/express-es6-template-engine#9]
In the README docs, it is mentioned that when defining a Route, an extension is expected unless a view engine has be defined. And that if a view engine is defined the extension can be safely omitted.

I'm finding that the same goes for defining a partials template. I spent quite some time trying to debug a "ENOENT: no such file or directory, open 'template.html'" when setting up my routes.

`app.set('view engine', 'html');

...

res.render('index', {

    locals: {

      title:  'Welcome!'

    },

    partials: {

      template: 'template.html'

    }

  });`

The above example throws errors for me unless I change the template definition to:
`...

    partials: {

      template: 'template'

    }

...`
This should be made a bit clearer in the docs to save others some confusion and time.

**Comment by dondido** [comment]
Hey @theFuzzyWarble sorry for wasting your time and thank you for spotting it - I guess the reason for this is the outdated README doc. Will be fixed shortly.

**Comment by theFuzzyWarble** [comment]
Good to know, I'll be checking back regularly. Thanks!
Also, it's never a waste of time, as I [re]learned that much more in working through it.
